#!/usr/bin/env python3
"""Create the reference-faithful, client-customizable Bid Builder DOCX template."""

from pathlib import Path

from docx import Document
from docx.enum.table import WD_CELL_VERTICAL_ALIGNMENT, WD_TABLE_ALIGNMENT
from docx.enum.text import WD_ALIGN_PARAGRAPH
from docx.oxml import OxmlElement
from docx.oxml.ns import qn
from docx.shared import Inches, Pt, RGBColor


def set_widths(table, widths):
    table.autofit = False
    for row in table.rows:
        for cell, width in zip(row.cells, widths):
            cell.width = Inches(width)


def left_rule(cell):
    borders = OxmlElement("w:tcBorders")
    left = OxmlElement("w:left")
    left.set(qn("w:val"), "single")
    left.set(qn("w:sz"), "5")
    left.set(qn("w:color"), "5BC0DE")
    borders.append(left)
    cell._tc.get_or_add_tcPr().append(borders)


def main() -> None:
    output = Path(__file__).resolve().parent.parent / "assets/proposal-template.docx"
    doc = Document()
    section = doc.sections[0]
    section.top_margin = Inches(0.32)
    section.bottom_margin = Inches(0.82)
    section.left_margin = Inches(0.34)
    section.right_margin = Inches(0.34)
    section.footer_distance = Inches(0.16)
    doc.styles["Normal"].font.name = "Arial"
    doc.styles["Normal"]._element.rPr.rFonts.set(qn("w:ascii"), "Arial")
    doc.styles["Normal"]._element.rPr.rFonts.set(qn("w:hAnsi"), "Arial")
    doc.styles["Normal"].font.size = Pt(9)

    masthead = doc.add_table(rows=1, cols=2)
    masthead.alignment = WD_TABLE_ALIGNMENT.LEFT
    set_widths(masthead, [4.35, 3.47])
    logo = Path(__file__).resolve().parent.parent / "assets/company-logo.jpg"
    masthead.cell(0, 0).paragraphs[0].add_run().add_picture(str(logo), width=Inches(3.35))
    contact = masthead.cell(0, 1)
    contact.vertical_alignment = WD_CELL_VERTICAL_ALIGNMENT.CENTER
    left_rule(contact)
    run = contact.paragraphs[0].add_run(
        "1220 South Pasadena, Mesa, AZ 85210\n"
        "480-969-6606    www.partitionsco.com\n"
        "ROC # CR60 110352    Tax ID#07370669"
    )
    run.font.name = "Arial"
    run.font.size = Pt(9)

    note = doc.add_paragraph()
    note_run = note.add_run("Proposal body is generated by BID Builder.")
    note_run.font.name = "Arial"
    note_run.font.size = Pt(9)
    note_run.font.italic = True
    note_run.font.color.rgb = RGBColor(89, 89, 89)

    footer = section.footer.paragraphs[0]
    footer.alignment = WD_ALIGN_PARAGRAPH.JUSTIFY
    footer_run = footer.add_run(
        "Customer-specific terms and conditions are inserted by the proposal generator from the approved clause profile."
    )
    footer_run.font.name = "Arial"
    footer_run.font.size = Pt(5.5)
    doc.save(output)
    print(output)


if __name__ == "__main__":
    main()
